# Mid-term Exam

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github//afarbin/DATA1401-Spring-2020/blob/master/Exams/Mid-term/Exam.ipynb)

Add cells to this notebook as you need for your solutions and your test of your solutions.

1. Write a function `first_alphabetically(lst)` that takes a list `lst` of strings and returns the string that is alphabetically first. For example, calling your function with the list of states:

In [0]:
states=['Mississippi', 'Maryland', 'Delaware', 'Connecticut', 'Virginia', 'Utah', 'Kansas',
        'Wyoming', 'Indiana', 'Louisiana', 'Missouri', 'Illinois', 'Minnesota', 'Vermont', 
        'New Mexico', 'North Dakota', 'Wisconsin', 'Tennessee', 'New York', 'Oklahoma', 
        'Colorado', 'Pennsylvania', 'West Virginia', 'Alabama', 'Montana', 'Texas', 
        'Washington', 'Michigan', 'New Hampshire', 'Arkansas', 'Hawaii', 'Iowa', 
        'Idaho', 'Kentucky', 'Ohio', 'Nebraska', 'Alaska', 'Oregon', 'South Dakota', 
        'New Jersey', 'Florida', 'Georgia', 'Rhode Island', 'Arizona', 'Maine', 
        'South Carolina', 'California', 'Nevada', 'Massachusetts', 'North Carolina']



In [0]:
def first_alphabetical(lst):
    new_list = [i.upper() for i in lst]
    length = len(new_list) - 1
    flag = 1

    while flag:
        flag = 0             
        for items in range(0, length):
            if new_list[items] > new_list[items + 1]:
                record = new_list[items + 1]
                new_list[items + 1] = new_list[items]
                new_list[items] = record
                flag = 1
                result = new_list[0]
                final = result[0] + result[1:].lower()
    return final 

    

In [3]:
first_alphabetical(states)

'Alabama'

should return the string `"Alabama"`. Note that you can compare strings:

In [0]:
print("A">"B")
print("B">"A")
print("A">"a")
print("bca">"bbc")

False
True
False
True


Make sure your implementation isn't case sensitive. Do not use python's built-in `min`, `max`, `sort` or any other sort function you find.

2. Write a function `arg_first_alphabetically(lst)`, which does the same thing as in exercise 1 but returns the index of the first string alphabetically.

In [0]:
def arg_first_alphabetically(lst):
    new_list = [i.upper() for i in lst]
    length = len(new_list) - 1
    flag = 1

    while flag:
        flag = 0             
        for items in range(0, length):
            if new_list[items] > new_list[items + 1]:
                record = new_list[items + 1]
                new_list[items + 1] = new_list[items]
                new_list[items] = record
                flag = 1
                result = new_list[0]
                final = result[0] + result[1:].lower()

  
    
    for items in range(0, length):
      if final == lst[items]:
       
        return items

  
  

In [5]:
arg_first_alphabetically(states)

23

3. Use your result in question 2 to implement a function `arg_sort_alphabetically(lst)` that returns a list that is alphabetically sorted. Sorting can be accomplished by successively applying the function in question 1 and removing the first element alphabetically. You can remove an element from a list using `pop()`. Make sure your implementation isn't case sensitive. Do not use python's built-in `min`, `max`, `sort` or any other sort function you find.

In [0]:
def arg_sort_alphabetically(lst):
  new_list = [i.upper() for i in lst]
  length = len(new_list) - 1
  flag = 1

  while flag:
      flag = 0             
      for items in range(0, length):
          if new_list[items] > new_list[items + 1]:
              record = new_list[items + 1]
              new_list[items + 1] = new_list[items]
              new_list[items] = record
              flag = 1
          result = new_list[0]
              
          final = result[0] + result[1:].lower()

  for items in range(0, length):
    if final == lst[items]:
      res = items
  
  f = lst.pop(res)
  


  length = len(lst) - 1
  flag = 1

  while flag:
      flag = 0             
      for items in range(0, length):
          if lst[items] > lst[items + 1]:
              record = lst[items + 1]
              lst[items + 1] = lst[items]
              lst[items] = record
              flag = 1

  for i in range(0, length):
    alpha = lst[i]
    finall = alpha[0] + alpha[1:].lower()
    lst[i] = finall

  print (lst)


In [7]:
arg_sort_alphabetically(states)


['Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New hampshire', 'New jersey', 'New mexico', 'New york', 'North carolina', 'North dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode island', 'South carolina', 'South dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West virginia', 'Wisconsin', 'Wyoming']


4. Implement a function `outer_product` that takes two one-dimensional lists of numbers and returns the two-dimensional outer product matrix defined as:

\begin{equation*}
\begin{pmatrix} x_1\\x_2\\ \vdots \\x_m \end{pmatrix} \begin{pmatrix} y_1&y_2& \dots &y_n\end{pmatrix} =
\begin{pmatrix}
x_1y_1 & x_1y_2 & \dots & x_1y_n\\
x_2y_1 & x_2y_2 & \dots & x_2y_n\\
\vdots & \vdots & \ddots & \vdots \\
x_my_1 & x_my_2 & \dots & x_my_n
\end{pmatrix}
\end{equation*}

In other words the elements of matrix C which is the outer product of A and B are $c_{ij} = a_i b_j$.

In [0]:
import numpy as np
def outer_product(lst1, lst2):
  a = np.array([lst2]).reshape(3,1)
  b = np.array([lst1]).reshape(1,3)
  print(a.dot(b))

In [9]:
outer_product([1,2,3],[1,2,3])

[[1 2 3]
 [2 4 6]
 [3 6 9]]



5. Implement a function `cumulative_sum(lst)` that takes a list of numbers and returns a list of same size where the element `i` is the sum of the elements `0` to `i` of the input list. For example given `[1,2,3]`, you should return [1,3,6].

In [0]:
def cumulative_sum(lst):

  length = len(lst)
  
  for i in range(0, length):
    if i>0 and i<=length:
      sum = lst[i] + lst[i-1]
      lst[i] = sum

  print (lst)




In [11]:
cumulative_sum([1,2,3,4,5])

[1, 3, 6, 10, 15]


6. Imagine you have a normal distributed random variable `x`. For example `x` can be grades on this exam. Using the normal distribution generator and histogram functions from lecture (provided below) and `cumulative_sum` from previous question to compute what is the value of `x_{90}` in $\sigma$ such that 90% of the values $x$ are below `x_{90}`. In other words:

$$
\int_{-\infty}^{x_{90}} N(x;\mu=0,\sigma=1) dx = 0.9
$$

In [0]:
def generate_normal(N,m=0,s=1):
    out = list() 
    
    while len(out)<N:
#    for _ in range(int(float(N)/2)+1):
        U1=random.random()
        U2=random.random()
    
        out.append(s*math.sqrt(-2*math.log(U1))*math.cos(2*math.pi*U2)+m)
        out.append(s*math.sqrt(-2*math.log(U1))*math.sin(2*math.pi*U2)+m)

    return out[:N]

def histogram(data, n_bins=10,x_min=None, x_max=None):
    if x_min==None:
        x_min=min(data)
    if x_max==None:
        x_max=max(data)
        
    bin_edges = arange(x_min,x_max,n_bins)
    bin_edges.append(x_max)

    hist=[0]*n_bins
    
    for d in data:
        for i in range(n_bins):
            if d>=bin_edges[i] and d<bin_edges[i+1]:
                hist[i]+=1
                break
                
    return hist,bin_edges

